### ISSUE TITLE
[HOTFIX] Fix Playwright module resolution - Install locally instead of globally

### ISSUE THREAD

**Issue by edcet** [edcet/perplexity-library-power-overlay#6]
## 🔥 Critical: Tests are STILL failing after PR #5

**Related**: #4 (CRITICAL UPDATE comment)

### Problem

All E2E tests in workflow runs #1-4 are failing with:

```
Error: Cannot find module '@playwright/test'
Require stack:
- /home/runner/work/perplexity-library-power-overlay/perplexity-library-power-overlay/playwright.config.ts
```

**Root Cause**: 
- Playwright packages installed **globally**: `npm -g i playwright@1.48.2 @playwright/test@1.48.2`
- Config file imports from **local** project: `import { defineConfig, devices } from '@playwright/test'`
- Node.js cannot resolve module from global installation

**Impact**:
- ❌ No E2E tests have successfully executed in any workflow run
- ❌ Jobs show "success" due to `|| echo "TESTS_FAILED=1"` fallback
- ❌ Overlay functionality completely unvalidated
- ❌ All test coverage requirements blocked (see #3)
- ❌ No HTML test reports generated

### Solution

**RECOMMENDED APPROACH**: Install Playwright locally

Update `.github/workflows/ci-e2e-overlay.yml`:

```yaml
- name: Install Playwright
  run: |
    npm init -y  # Create package.json if not exists
    npm i playwright@1.48.2 @playwright/test@1.48.2  # Remove -g flag
    npx playwright install chromium firefox webkit
```

This will:
1. Install packages to local `node_modules/`
2. Allow config to import `@playwright/test` successfully
3. Enable proper test execution and reporting
4. Generate HTML artifacts for download

### Alternative Approaches

**Option 2**: Use npx with global install (less reliable)
```yaml
- name: Run Playwright tests
  run: npx --yes playwright test --project=${{ matrix.browser }}
```

**Option 3**: Add package.json to repo
- More maintainable long-term
- Better dependency management
- Enables version locking

### Acceptance Criteria

- [ ] Workflow runs without module resolution errors
- [ ] All 3 browser jobs (chromium/firefox/webkit) execute tests successfully
- [ ] Playwright HTML report artifacts uploaded and downloadable
- [ ] Test output shows actual test execution (not just setup steps)
- [ ] No `TESTS_FAILED` environment variables set in successful runs

### Next Steps

1. Create hotfix branch: `hotfix/playwright-local-install`
2. Update workflow file with local installation
3. Test locally if possible: `npx playwright test`
4. Create PR and link to this issue
5. Verify workflow Run #5 executes tests successfully
6. Review HTML test reports for any actual test failures
7. Update #3 with coverage results
8. Move to Kanban "In Progress"

### Priority

🔥 **CRITICAL** - Blocking all E2E validation and overlay QA

### Labels

- `bug`
- `ci`
- `critical`
- `hotfix`

### Assignee

@edcet

### Timeline

**ETA**: 30 minutes (simple workflow file change)

**Comment by edcet** [comment]
✅ **Branch Created**: `6-hotfix-fix-playwright-module-resolution---install-locally-instead-of-globally`

**Next Step**: Update `.github/workflows/ci-e2e-overlay.yml` to install Playwright locally:

```yaml
- name: Install Playwright
  run: |
    npm init -y  # Create package.json if not exists
    npm i playwright@1.48.2 @playwright/test@1.48.2  # Remove -g flag
    npx playwright install chromium firefox webkit
```

**Action Required**: Create PR with this change and validate that all 3 browser jobs execute tests successfully.

**Status**: Ready for PR creation - branch is available for checkout.
